# Site settings
title: Dream Team Reads
url: "http://dreamteamreads.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  Read, Review, Repeat is out mantra. Bringing you book reviews, adventures and literary tidbits is our M.O.

# Your information
email: dreamteamreads@gmail.com
author: Olivia & Sarah
avatar: "/assets/avatar.png"
profile: |
  Two book-loving, wanderlusting, language learning Canadian girls who form one hell of a team. &#35;DreamTeamReads. <br />
  We post Tuesdays and Thursdays.
twitter_username: dreamteamreads
instagram_username: dreamteamreads
#github_username:  github_username

disqus_shortname: dreamteamreads

permalink: pretty
gems:
 - jekyll-paginate
 - jekyll-gist
# - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

host: 0.0.0.0

excerpt_separator: <!--more-->

kramdown:
  input: GFM
  syntax_highlighter: rouge
